<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Type_of_loan</name>
   <tag></tag>
   <elementGuidId>944224a7-8aa3-4fbb-a0e8-cdeccae4cb94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='loan_application_mortgage_type_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='loan_application_mortgage_type_1']</value>
   </webElementProperties>
</WebElementEntity>
