<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Back</name>
   <tag></tag>
   <elementGuidId>01fdb1fa-7a3b-48c2-9c8d-671b1fe81231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='loan_application_form']/div[7]/div[4]/div[2]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
