<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_Tutorial-borrower</name>
   <tag></tag>
   <elementGuidId>6756bae9-44b3-4fd6-b480-0d95fedba6a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='tutorial-borrower']/div[2]/div[1]/div</value>
   </webElementProperties>
</WebElementEntity>
